### PR TITLE
v-hotkey 1.0.0 - refactor

### PR DESCRIPTION
**Pull request by zcuric**
### This PR
- [x] Updates dependencies
- [x] Use Vue CLI instead of classic webpack 🛠 
  - for build process
  - for dev process
  - for buidling docs
- [x] Adds basic tests ✨ 
- [x] Lints all the things using `eslint-plugin-vue` :nail_care:
- [x] Docs now have high-res and updated [background image ](https://unsplash.com/photos/q10VITrVYUM )😍 
- [x] Solves #16 
- [x] Refactors almost everything
- [x] No breaking changes ❗️ Directive works the same as it was < 1.0.0.

Notes:
- Build destination is now in `dist` folder, your internal publishing should be adjusted. I suggest using [Sindres `np`](https://github.com/sindresorhus/np) for easier publishing.
- Also build process for docs have been changed. Build destination is now `docs/dist`. This also should be updated for the package website.

### CODE REVIEW

**Comment by Dafrok** [comment]
Great work.

**Comment by Dafrok** [comment]
Great work. But I don't think the major version can be added yet, there're some issues remain unresolved.

**Comment by zcuric** [comment]
@Dafrok Thanks! Please link the issues. I'll try to address them in the upcoming PR. 😉

**Comment by zcuric** [comment]
@Dafrok please don't forget about the PR notes - build process and docs.

**Comment by Dafrok** [comment]
New version has been published, thx for your work!

**Pull request merged**
