### PR TITLE
add details on default usage

### PR DESCRIPTION
**Pull request by shershen08**
because if I use it like this
```
      enter: {
          keyup: this.doSomeLogicOnPressEnter,
        }
```
see, only keyup and no keydown - I get error

### CODE REVIEW

**Comment by Dafrok** [comment]
There might be a better solution if give a `noop` function as default handler. What do u think about?

**Comment by shershen08** [comment]
yes, if you can fix it in code - is even better
I was just proposing quick fix in the docs, so that users of the lib don't get error  
but code is def better

**Comment by Dafrok** [comment]
Ok, that fix is coming soon

**Comment by Dafrok** [comment]
enjoy ver 0.3.1 😄

**Pull request closed without merging**
