### PR TITLE
Add support for separate keyup and keydown listeners per key. (with examples in README and docs)

### PR DESCRIPTION
**Pull request by JZumun**
Hi!

I discovered this project today and it looks great! I was planning to use v-hotkey for one of my projects, but one of my requirements was to set a value when a key is being held. That is to say, set the value on keydown, and unset it on keyup.

While v-hotkey didn't support it out of the box, I found that it wasn't difficult to extend it to support the syntax: 

```javascript
{
  keymap: {

    //original way
    'key1': this.keyMethod

    //object extension
    'key2': {
       keydown: this.keydownMethod
       keyup: this.keyupMethod
    }
  }
}
```

I've tried to minimize the performance penalty by conditionally adding the listener to the keyup event only if a keyup method is registered in the keymap. However, I think some optimizations still may be possible.

I've also taken the liberty to add examples of the new syntax to the Readme and the docs (I had to renumber the steps to place it somewhere i thought was appropriate, sorry 😞  ) Please feel free to revert those changes as you see fit.

In addition to the above feature added, I added **stylus** and **stylus-loader** as dev dependencies, because `npm run dev`  would fail without it. I've also changed `npm run build` to make use of the webpack configuration present in the root folder (running `npm run build` without the changes resulted in a drastically different _index.js_ than the one present). Once again, please feel free to revert the change as needed.

Thank you for taking the time to consider this!

### CODE REVIEW

**Comment by Dafrok** [comment]
Thank you for your contribution!
It seems wonderful and I just happened to be thinking about this feature. Give me some more time to review your commits.

**Comment by Dafrok** [comment]
Well, the example of key combination has been removed in your commits, it's not so good. I think the better way is add one page for the new feature.

**Comment by Dafrok** [comment]
By the way, there's no need to build the docs and libs, I would do it before release.

**Comment by Dafrok** [comment]
Hmmm, the indentation of source code should be 2 instead of 4. I think eslint is nessasery, I will add it to dependencies soon.

**Comment by Dafrok** [comment]
https://github.com/Dafrok/v-hotkey/commit/14a52caabcfbf17e90269378dc7e2d0fe61cc214

**Comment by Dafrok** [comment]
https://github.com/Dafrok/v-hotkey/commit/14a52caabcfbf17e90269378dc7e2d0fe61cc214 added eslint for this project, it also causes such a lot of conflicts. If trouble to you, I will resolve them in time.

**Comment by JZumun** [comment]
Hi @Dafrok ! Thank you for taking your time to review my commits! 

Regarding the documentation, I did add a page for the Keyup and Keydown listeners 😄 . In https://github.com/JZumun/v-hotkey/commit/15a81c6d9bacac8d3b597794cc1c4881edfb4e4d what i did was move Key Combinations to step 4, Private Hot Keys to step 5, and the final page to step 6, making the Keyup and Keydown Listeners the new step 3. 

Good call on the eslint, as well! Don't worry, I'll handle the resolving!

Thank you!

**Comment by JZumun** [comment]
Alright! Thank you! Keep up the great work 😄

**Pull request merged**
